# GitHub Actions workflow for deploying Python app on main branch merge
name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Add your deployment commands here
          # Example:
          # cd /path/to/your/app
          # git pull origin main
          # source venv/bin/activate
          # pip install -r requirements.txt
          # systemctl restart my-app
          echo "Deployment successful!"

    - name: Send email notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: 'Deployment Successful: ${{ github.repository }}'
        body: file://cicd-setup/assets/notifications/email_notification_template.txt
        to: user@example.com
        from: GitHub Actions <actions@github.com>
